apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: gcr.io/hw3-414922/sa-frontend:latest
      name: sa-frontend
      ports:
        - containerPort: 80